# ==================================================
#  C E N T A U R  ::  MOS
#  Middle East Oil Security Simulator
#
#  Prithwis Mukerjee | 2026
#  Action -> Consequence -> Reaction -> ...
# ==================================================

import json

from mos import callLLM


class Centaur_Agent:
    """
    Adjudication agent for MOS.

    Centaur receives:
        - current WorldState
        - current Trigger Event
        - candidate Events generated by Chanakya

    Centaur assigns one relative simulation weight to each
    candidate Event.

    Centaur does NOT:
        - generate candidate Events
        - modify candidate Events
        - select the Reaction
        - assign event IDs
        - append anything to E
        - update the WorldState

    The returned weights are simulation weights, not calibrated
    real-world probabilities.
    """


    # --------------------------------------------------------
    # Initialise Centaur
    # --------------------------------------------------------

    def __init__(
        self,
        agent_id,
        generic_role,
        adjudication_role
    ):

        self.agent_id = agent_id
        self.generic_role = generic_role
        self.adjudication_role = adjudication_role


    # --------------------------------------------------------
    # Display Centaur identity
    # --------------------------------------------------------

    def show(self):

        print(f"Centaur : {self.agent_id}")


    # --------------------------------------------------------
    # Convert Trigger Event to text
    # --------------------------------------------------------

    def _event_to_text(self, event):

        return f"""
Event ID  : {event.event_id}
Actor     : {event.actor}
Action    : {event.action}
Rationale : {event.rationale}
""".strip()


    # --------------------------------------------------------
    # Convert WorldState to text
    # --------------------------------------------------------

    def _world_to_text(self, world):

        lines = [
            f"WorldState: {world.state_id}",
            ""
        ]

        for v in world.variables:

            lines.append(f"VARIABLE: {v.name}")
            lines.append(f"Index: {v.index}")
            lines.append(f"Status: {v.status}")

            if v.conditions:

                lines.append("Conditions:")

                for condition in v.conditions:
                    lines.append(f"- {condition}")

            lines.append("")

        return "\n".join(lines)


    # --------------------------------------------------------
    # Convert Candidate Events to text
    # --------------------------------------------------------

    def _candidates_to_text(self, candidates):

        lines = []

        for i, candidate in enumerate(candidates):

            lines.append(f"CANDIDATE {i}")
            lines.append(f"Actor     : {candidate.actor}")
            lines.append(f"Action    : {candidate.action}")
            lines.append(f"Rationale : {candidate.rationale}")
            lines.append("")

        return "\n".join(lines)


    # --------------------------------------------------------
    # Evaluate Candidate Events
    # --------------------------------------------------------

    def evaluate(
        self,
        client,
        model,
        trigger,
        world,
        candidates,
        effort="medium"
    ):

        print(f"Centaur working ---------- {self.agent_id}")

        trigger_text = self._event_to_text(trigger)
        world_text = self._world_to_text(world)
        candidates_text = self._candidates_to_text(candidates)


        # ----------------------------------------------------
        # System Prompt
        # ----------------------------------------------------

        system_prompt = f"""
============================================================
GENERIC CENTAUR ROLE
============================================================

{self.generic_role}


============================================================
ADJUDICATION ROLE
============================================================

CENTAUR AGENT : {self.agent_id}

{self.adjudication_role}
""".strip()


        # ----------------------------------------------------
        # User Prompt
        # ----------------------------------------------------

        user_prompt = f"""
============================================================
TRIGGER EVENT
============================================================

{trigger_text}


============================================================
CURRENT WORLDSTATE
============================================================

{world_text}


============================================================
CANDIDATE EVENTS
============================================================

{candidates_text}


============================================================
TASK
============================================================

Evaluate the relative plausibility of each Candidate Event
given the Trigger Event and Current WorldState.

Assign one non-negative simulation weight to every Candidate
Event.

The weights represent relative plausibility within this
simulation. They are NOT calibrated real-world probabilities.

Do NOT generate additional Candidate Events.
Do NOT modify the Candidate Events.
Do NOT select the Reaction.
Do NOT update the WorldState.


============================================================
OUTPUT FORMAT
============================================================

Return ONLY valid JSON as a list of numbers.

The number of weights must exactly equal the number of
Candidate Events.

Example:

[0.65, 0.35]
""".strip()


        # ----------------------------------------------------
        # Call LLM
        # ----------------------------------------------------

        response = callLLM(
            client,
            system_prompt,
            user_prompt,
            model,
            effort
        )


        # ----------------------------------------------------
        # Parse LLM response
        # ----------------------------------------------------

        if isinstance(response, str):
            weights = json.loads(response)
        else:
            weights = response


        # ----------------------------------------------------
        # Basic structural validation
        # ----------------------------------------------------

        if len(weights) != len(candidates):
            raise ValueError(
                "Centaur returned a different number of weights "
                "than Candidate Events."
            )

        if any(w < 0 for w in weights):
            raise ValueError(
                "Centaur returned a negative simulation weight."
            )

        if sum(weights) <= 0:
            raise ValueError(
                "Centaur returned no positive simulation weight."
            )

        # ----------------------------------------------------
        # Normalise simulation weights
        # ----------------------------------------------------

        total = sum(weights)
        weights = [w / total for w in weights]



        return weights
# ============================================================
import random

def Shakuni(candidates, weights):

    selected_index = random.choices(
        range(len(candidates)),
        weights=weights,
        k=1
    )[0]

    reaction = candidates[selected_index]
    reaction.selection_weight = weights[selected_index]

    return reaction